name: Create Develop Quest
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "ギルドマスター"
          args: "新しいクエストが発生しました！\nQuest.${{ github.event.issue.number }} ${{ github.event.issue.title}}\n${{ github.event.issue.html_url }}"
