name: deploy-develop
on:
  push:
    branches: develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            /home/oshowjp/kimono-cms.net/application/tools/deploy.sh
            /home/oshowjp/o-show.xyz/application/tools/deploy/shin-rental-server/kimono.sh
